// Dicionário de tipos de produto do nicho MATERNIDADE/BEBÊ.
// Semeado da árvore de categorias 'Bebês' do Mercado Livre (metadados) + sinônimos.
// Autocomplete do cadastro de palavras-chave. Sem variações de tamanho/modelo.
export const NICHE_TERMS_MATERNIDADE: string[] = [
  "absorvente de seio",
  "alimentação",
  "alimentos",
  "almofadas",
  "almofadas para amamentação",
  "amamentação",
  "andador",
  "aquecedores de mamadeiras",
  "aspirador nasal",
  "assentos para banheiras",
  "babador",
  "babá eletrônica",
  "balanços",
  "banheira",
  "banho",
  "bebê conforto",
  "berço",
  "bicicletas sem pedais",
  "biscoitinhos",
  "blusas",
  "body",
  "bolas",
  "bolsas",
  "bomba de tirar leite",
  "bonecos de atividades",
  "brinquedos",
  "brinquedos de empurrar",
  "brinquedos para banho",
  "cadeira para carro",
  "cadeiras de alimentação",
  "cadeiras de balanço",
  "cadeirinha",
  "calçados",
  "calças",
  "camisas",
  "camisetas",
  "canguru",
  "cantos",
  "capacetes",
  "carrinho de bebê",
  "casacos",
  "cercadinho",
  "cereal",
  "chapéus para banho",
  "chocalho",
  "chupeta",
  "chupeta alimentadora",
  "chupeta termômetro",
  "chupetas",
  "chá de bebê",
  "cobertor",
  "colares para dentição",
  "colchão para berço",
  "coleira de pulso",
  "colônia",
  "condicionador",
  "copo",
  "copo de transição",
  "cortador de unha",
  "cotonete",
  "creme",
  "cubos didáticos",
  "cuidados com o bebê",
  "culotes",
  "descanso",
  "empilhar",
  "enfeites de porta",
  "escovas de dentes",
  "espelhos para carros",
  "esponja de banho",
  "esterilizador",
  "esterilizador de chupetas",
  "esterilizadores",
  "esterilizadores manuais",
  "extensores de torneiras",
  "faixa para gestante",
  "fralda",
  "fralda de pano",
  "fralda ecológica",
  "fraldas de boca",
  "grades",
  "grades para cama",
  "hidratante",
  "higiene",
  "joelheiras",
  "jogos de encaixe",
  "jogos de quarto",
  "kit higiene",
  "kits",
  "labirintos",
  "leite infantil",
  "lenço umedecido",
  "luva",
  "macacão",
  "mamadeira",
  "manta",
  "maternidade",
  "meia",
  "mesas de atividades",
  "mictórios",
  "mochilas",
  "moda praia",
  "moisés",
  "moletons",
  "monitor de bebê",
  "mordedor",
  "mordedores",
  "máquinas de ruído branco",
  "móbiles",
  "naninha",
  "ninho redutor",
  "organizadores de brinquedos",
  "organizadores de fraldas",
  "organizadores para carros",
  "pantufa",
  "papinha",
  "passeio",
  "pelúcia",
  "pente",
  "pijama",
  "pomada",
  "pomada de assadura",
  "porta chupeta",
  "porta dentes de leite",
  "porta fralda",
  "prato",
  "prendedor de chupeta",
  "protetor de berço",
  "protetor solar infantil",
  "protetores de berço",
  "protetores de quinas",
  "protetores de seios",
  "protetores de tomada",
  "protetores para cintos",
  "protetores solares para carros",
  "puxar",
  "quadrados de algodão",
  "quarto",
  "redes",
  "redutores",
  "regatas",
  "repelente",
  "roupa para gestante",
  "roupas",
  "roupões",
  "roupões de banho",
  "sabonete",
  "sacos de dormir",
  "sacos para leite materno",
  "saias",
  "saídas maternidade",
  "saúde",
  "segurança",
  "shampoo",
  "shorts",
  "suéteres",
  "talco",
  "talher",
  "tapete eva",
  "tapetes antimpacto",
  "tapetes de atividades",
  "termômetro",
  "termômetros de banho",
  "toalha de banho",
  "toalha umedecida",
  "torres de aprendizagem",
  "touca",
  "travas de segurança",
  "triciclo",
  "trocador",
  "trocadores para cômoda",
  "trocadores portáteis",
  "troninhos",
  "vestidos",
  "óleo"
];
